name: madu_gate_app
description: App mobile do Madu Gate
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

flutter_native_splash:
  color: "#050B1D"
  image: assets/logo/madu_logo.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#050B1D"
    image: assets/logo/madu_logo.png
